#ifndef ___SDKCONFIG_H
#define ___SDKCONFIG_H

#define CONFIG_ESP_MAIN_TASK_STACK_SIZE 32768
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES 1
#define CONFIG_LOG_MAXIMUM_LEVEL CONFIG_LOG_MAXIMUM_LEVEL_INFO

#endif

